name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Setup NodeJS
      uses: actions/setup-node@v1.4.1
      with:
        node-version: 12.x

    - name: Setup Python
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 2.x
        architecture: x64

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.0

      # The steps are ordered based on least likely to change to most likely to change.
      # It makes CICD much more efficient with caches.

    - name: Build flatbuffer definitions
      run: yarn build-flatbuffers

    - name: Install packages
      run: yarn install

    - name: Build overlay DLL
      run: yarn build-overlay

    - name: Build native node module
      run: yarn build-native

    - name: Build main process
      run: yarn build-main

    - name: Build renderer process
      run: yarn build-renderer

    - name: Package
      run: yarn package-no-build